version: "3"
services:
  authenticate-context:

    build:
      context: .
      dockerfile: Dockerfile
    container_name: authenticate-context

    env_file:
      - .env
    ports:
      - "4200:4200"
    